### ISSUE TITLE
TypeError: Cannot call method 'postMessage' of undefined

### ISSUE THREAD

**Issue by frdmn** [PoshCode/slack-irc-plugin#4]
Hey @Jaykul 

first of all, awesome work on this fork!

However, I have a little issue as soon as I start the bot... It connects and joins fine into my key (+k) protected channel, but as soon as I try to write a message in IRC, the bot interrupts with the following error message:

```
[Fri Feb 20 2015 10:27:25 GMT+0000 (UTC)] INFO Connecting...
[Fri Feb 20 2015 10:27:26 GMT+0000 (UTC)] INFO Slack client now logged in (U02A27R5E) as frdmn to YEAHWHAT?!
[Fri Feb 20 2015 10:27:27 GMT+0000 (UTC)] INFO Slack client now connected
[Fri Feb 20 2015 10:27:36 GMT+0000 (UTC)] INFO IRC_MSG> #yeahwhat_admin: frdmn: helllo
[Fri Feb 20 2015 10:27:36 GMT+0000 (UTC)] INFO SLACK> undefined: frdmn (irc): helllo

/tmp/slack-irc-plugin/node_modules/irc/lib/irc.js:759
                    throw err;
                          ^
TypeError: Cannot call method 'postMessage' of undefined
    at Bot.slackSpeak (/tmp/slack-irc-plugin/lib/bot.js:310:13)
    at Client.<anonymous> (/tmp/slack-irc-plugin/lib/bot.js:192:14)
    at Client.EventEmitter.emit (events.js:106:17)
    at Client.<anonymous> (/tmp/slack-irc-plugin/node_modules/irc/lib/irc.js:517:22)
    at Client.EventEmitter.emit (events.js:95:17)
    at iterator (/tmp/slack-irc-plugin/node_modules/irc/lib/irc.js:756:22)
    at Array.forEach (native)
    at Socket.<anonymous> (/tmp/slack-irc-plugin/node_modules/irc/lib/irc.js:752:15)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:736:14)
```

Any ideas?

**Comment by frdmn** [comment]
It might be worth mentioning, that I also had issues with the original project (@jimmyhillis' version), as stated here: https://github.com/jimmyhillis/slack-irc-plugin/issues/18

This might be related to the issue here.

**Comment by Jaykul** [comment]
90% sure it's a configuration problem (which I should fix in code, but my imagination ran out when I was trying to decide how to fix it). You need to make sure the channels are all in **lowercase** for it to work.

The crash indicates 

```
TypeError: Cannot call method 'postMessage' of undefined
    at Bot.slackSpeak (/tmp/slack-irc-plugin/lib/bot.js:310:13)
```

Which is the last line of the slackSpeak function:

```
var channel = self.slacker.getChannelByName(channel);

message.parse = 'full'
message.link_names = 1
message.unfurl_links = 1

channel.postMessage(message)
```

Obviously self.slacker.getChannelByName didn't return your channel for some reason.  `self.slacker` is the `slack-client` code from slack, so that shouldn't be the problem, but `channel` is being passed from the calling code:

```
    from = self._usermap.nicks[from] || from
    to = self.config.channels[to.toLowerCase()]
    message = self.prepareMessage(message, self._usermap.nicks)

    self.slackSpeak(to, message, from)
```

Where 'to' is the IRC channel as sent by your server.

So there are only two possible problems that I can think of:
1. The most likely thing is that your channel name isn't all lowercase, so it doesn't match `to.toLowerCase()`
2. The next option would be that your IRC server doesn't send the channel with '#' prefixed (but that seems unlikely)

**Comment by frdmn** [comment]
@Jaykul I did a bit of testing. When i try to console log the input variables of `slackSpeak()`, the `to` variable is undefined.

So i just hardcoded my channel from the config.js file in there:

```
self.slackSpeak("#admin", message, from)
```

But i still ended up getting the `TypeError: Cannot call method 'postMessage' of undefined` error. Then however, i tried the channel name without the hash and it worked fine:

```
self.slackSpeak("admin", message, from)
```

Here's an extract of my channel configuration:

```
channels: {
    '#yeahwhat_admin channelkey': '#admin'
},
```

**Comment by Jaykul** [comment]
Yeah, I need to put some config cleanup code in to convert this stuff to what works. Currently the slack channel must NOT have the # and both have to be lowercase.  There's a comment to that effect in config-example.js, but it would be better to sanitize the settings.

``` js
channels: {
   '#ircchannel password', 'slackchannel'
}
```

**Comment by frdmn** [comment]
@Jaykul I tried that, but `to` is still undefined if i skip the hash symbol in the config.js:

```
[Sun Feb 22 2015 08:48:13 GMT+0100 (CET)] INFO SLACK> undefined: frdmn (irc): test
```

Edit: Ha! Found out why. Whenever i use a channel key, the bot can't parse the Slack channel properly. This works fine:

```
channels: {
    '#yeahwhat_admin2': 'admin'
},
```

**Comment by Jaykul** [comment]
Oh, I know!. It's the password. The code is looking up the slack channel
from the irc channel, but your config has a password in it, so it doesn't
match!

I'll have to do that in the "sanitizing" code I mentioned I think it's
needed: copy the channels to a new array without the passwords, and force
them to lower case for consistency.

## 

On Sunday, February 22, 2015, Jonas Friedmann notifications@github.com
wrote:

> @Jaykul https://github.com/Jaykul I tried that, but to is still
> undefined if i skip the hash symbol in the config.js:
> 
> [Sun Feb 22 2015 08:48:13 GMT+0100 (CET)] INFO SLACK> undefined: frdmn (irc): test
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PoshCode/slack-irc-plugin/issues/4#issuecomment-75424369
> .

## 

## 

Joel "Jaykul" Bennett
http://HuddledMasses.org
PowerShell MVP, Software Dev., Speaker
585-563-9632 <//1-585-563-9632> | Jaykul @ GitHub
https://github.com/jaykul | Twitter https://twitter.com/Jaykul | Linked
_In_ http://www.linkedin.com/in/jaykul/ http://PowerShellGroup.org

**Comment by frdmn** [comment]
Thanks! I did this dirty hack to get it working so far:

```
// Temporary channel object without IRC channel passwords
Object.keys(this.config.channels).forEach(function(key) {
    var plainChannel = key.split(" ")[0];
    self.config.plainChannels = {};
    self.config.plainChannels[plainChannel] = self.config.channels[key];
});
```

However, I think the channel key feature is responsible for my other issue (#7) as well. I'll elaborate more over there.
