### ISSUE TITLE
Slack messages doesn't show up in IRC

### ISSUE THREAD

**Issue by frdmn** [PoshCode/slack-irc-plugin#7]
Now since I got the plugin working, I noticed that messages sent from Slack doesn't show up in IRC.

IRC to Slack works fine so far.

Any ideas?

**Comment by Jaykul** [comment]
Best guess is you haven't invited the bot into the channel.  Even when they're talking to the channel, they don't "join" it unless you invite them, and they don't see anything that's said until they join.

**Comment by frdmn** [comment]
I'm not quite sure how to do this. 

Can you tell me where i can add/invite the bot into my channel?

**Comment by frdmn** [comment]
@Jaykul Okay, since i've stripped the channel key in my `plainChannels` object, msgs show up in IRC. Unfortunatly, those messages doesn't contain the actual message sent from Slack. No, instead it just sends only the plaintext channel key.

I am not quite sure why at the moment, though. 

However, I'll close both issues for now so I can create a new one, since the main problem in both issues is the channel key. :)
